name: gatsby

proxy:
  appserver:
    - gatsby.lndo.site:8000

services:
  appserver:
    type: node
    port: '8000'
    command: gatsby develop --host 0.0.0.0
  node:
    type: node
    build:
      - yarn policies set-version
      - yarn
    globals:
      gatsby-cli: latest
    overrides:
      environment:
        NODE_ENV: development
        GATSBY_WEBPACK_PUBLICPATH: gatsby.lndo.site

tooling:
  gatsby:
    service: appserver
  develop:
    description: Runs `gatsby develop`
    cmd:
      - appserver: gatsby develop --host 0.0.0.0 --port 8000
    user: root
  node:
    service: appserver
  npm:
    service: appserver
  yarn:
    service: appserver

# Tested with Lando version
version: v3.0.0-rc.22
