name: gatsby

proxy:
  appserver:
    - gatsby.lndo.site:8000

services:
  appserver:
    type: node
    port: '8000'
    build:
      - yarn global add gatsby-cli
      - yarn

tooling:
  develop:
    description: Runs `gatsby develop` as root with host & port options
    cmd:
      - appserver: gatsby develop --host 0.0.0.0 --port 8000
    user: root
  gatsby:
    service: appserver
  node:
    service: appserver
  npm:
    service: appserver
  yarn:
    service: appserver

# Tested with Lando version
version: v3.0.0-rc.22
